### ISSUE TITLE
Font size after 4xl has no effect

### ISSUE THREAD

**Issue by AshotN** [jaredh159/tailwind-react-native-classnames#74]
According to the tailwind docs here https://tailwindcss.com/docs/font-size

font size goes all the way to `text-9xl`
But after `text-4xl` there seems to be no effect.

**Comment by AshotN** [comment]
This is my `tailwind.config.js`

```
module.exports = {
  purge: [],
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {
      colors: {
       
        neutral: "#7e7c7f",
        slate: "#131313",
      },
      borderWidth: {
        1: "1",
      },
      backgroundOpacity: {
        8: "0.08",
      },
    },
  },
  variants: {
    extend: {},
  },
  plugins: [],
}

```

I don't see anything that would be causing it

**Comment by jaredh159** [comment]
what version of tailwind do you have installed? is it the latest?

**Comment by AshotN** [comment]
`"tailwindcss": "^2.2.17"`
`"twrnc": "^2.0.1"`

Nearly the latest

**Comment by jaredh159** [comment]
can you go to the file where you pass in your custom tailwind to the `create` function, and then, add a couple lines and then log, like this:

```js
import resolveConfig from 'tailwindcss/resolveConfig'; // 1️⃣   add this temporarily

// 2️⃣   next, pass your tailwind config to the `resolveConfig` function
const resolved = resolveConfig(require(`../../tailwind.config.js`)); // <- your path may differ

// 3️⃣  finally, console.log out the fontSize:
console.log(resolved.theme.fontSize)
```

Then paste the result of the console.log here in the issue.  When I try to replicate your issue, i get:

```
{
        xs: [ '0.75rem', { lineHeight: '1rem' } ],
        sm: [ '0.875rem', { lineHeight: '1.25rem' } ],
        base: [ '1rem', { lineHeight: '1.5rem' } ],
        lg: [ '1.125rem', { lineHeight: '1.75rem' } ],
        xl: [ '1.25rem', { lineHeight: '1.75rem' } ],
        '2xl': [ '1.5rem', { lineHeight: '2rem' } ],
        '3xl': [ '1.875rem', { lineHeight: '2.25rem' } ],
        '4xl': [ '2.25rem', { lineHeight: '2.5rem' } ],
        '5xl': [ '3rem', { lineHeight: '1' } ],
        '6xl': [ '3.75rem', { lineHeight: '1' } ],
        '7xl': [ '4.5rem', { lineHeight: '1' } ],
        '8xl': [ '6rem', { lineHeight: '1' } ],
        '9xl': [ '8rem', { lineHeight: '1' } ]
      }
```

Which shows that the config knows about all the way up to `9xl`.

**Comment by AshotN** [comment]
I just realized the problem. Since line height becomes 1 after 4xl the text was shifting out of view. Sorry for the trouble!

**Comment by peloycosta** [comment]
@jaredh159 I just had the same problem and came across this issue. I don't think this should be the intended behaviour.
Right now if you use `text-5xl` or above the line-height is set as 1 which effectively makes the text not appear unless you override that line-height.

For these font-sizes in particular the line-height in tailwind is set as 1 because on the web a unitless value represents a multiplier for the font-size. However for react-native this is not the case.
Currently we've fixed this by overriding those font-sizes and setting the line-height with the same value in rem on `tailwind.config.js`:
```
theme: {
  extend: {
    fontSize: {
      "5xl": ["3rem", { lineHeight: "3rem" }],
      "6xl": ["3.75rem", { lineHeight: "3.75rem" }],
      "7xl": ["4.5rem", { lineHeight: "4.5rem" }],
      "8xl": ["6rem", { lineHeight: "6rem" }],
      "9xl": ["8rem", { lineHeight: "8rem" }],
    },
  },
},
```

I think this shouldn't be need and that unitless values for the line-height on the tailwind config should be supported. If you think this makes sense I don't mind giving it a go and opening a PR.

**Comment by AshotN** [comment]
I assumed this was intentional since it seems the tailwind spec does the same thing. But glad it was changed!

**Comment by nassmim** [comment]
@jaredh159 got the same issue, I keep receiving `text-5xl` is not a valid Tailwind class name. 
I run what you initially asked and the config seems to know about it as they all appears all the way up to 9px. However it works until 4xl, then it doesn't above. 

When I change my config file, like  peloycosta suggested :
`
/** @type {import('tailwindcss').Config} */
module.exports = {
content: ["./src/**/**/*.{html,js}"],
  theme: {
    extend: {
        fontSize: {
          "5xl": ["3rem", { lineHeight: "3rem" }],
          "6xl": ["3.75rem", { lineHeight: "3.75rem" }],
          "7xl": ["4.5rem", { lineHeight: "4.5rem" }],
          "8xl": ["6rem", { lineHeight: "6rem" }],
          "9xl": ["8rem", { lineHeight: "8rem" }],
        },
      },      
  },
  plugins: [],
}

`
but it still does not work. 

I'm on "tailwindcss": "^3.2.4"

**Comment by jaredh159** [comment]
@nassmim that's strange. we have unit tests proving that `text-5xl` is a valid utility that generates the correct RN style objects.  i'm guessing something is amiss with your `tailwind.config.js` file. maybe you could try removing your custom config temporarily and see if the error goes away?  if it does, it's likely something about your config file. double check that it's shaped exactly the right way, or maybe post the whole thing here if you get stuck.

**Comment by nassmim** [comment]
@jaredh159 when I got this issue, I had no config yet. I created my config afterwards, when I read this thread. 

this is what I initially had:

```
import tw from 'tailwind-react-native-classnames';

export default {
 
    container: tw.style('h-full', 'items-center', 'py-24', 'bg-white', 'justify-between'),
    
    title: tw.style('text-3xl'),
      
    vehicleChoice: tw.style('w-72', 'flex-row', 'items-center', 'flex-wrap'),

    vehicleIcon: tw.style('text-5xl', 'mx-5', 'py-2'),
}
```

Once I searched online, I started my custom config:

```
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,js}"],
  theme: {
    extend: {
        fontSize: {
          "5xl": ["3rem", { lineHeight: "3rem" }],
          "6xl": ["3.75rem", { lineHeight: "3.75rem" }],
          "7xl": ["4.5rem", { lineHeight: "4.5rem" }],
          "8xl": ["6rem", { lineHeight: "6rem" }],
          "9xl": ["8rem", { lineHeight: "8rem" }],
        },
      },      
  },
  plugins: [],
}
```

(I also tried this above without the extend just in case but still not working)
The config file is at the project root and my js file are in ./src/screens/home/*.js

When I run your line of code : `console.table(resolved.theme.fontSize)`

I get results showing that the class exists, which makes me really confuse:


```
(index) | 0 | 1
-- | -- | --

2xl | '1.5rem' | {…}
3xl | '1.875rem' | {…}
4xl | '2.25rem' | {…}
5xl | '3rem' | {…}
6xl | '3.75rem' | {…}
7xl | '4.5rem' | {…}
8xl | '6rem' | {…}
9xl | '8rem' | {…}
base | '1rem' | {…}
lg | '1.125rem' | {…}
sm | '0.875rem' | {…}
xl | '1.25rem' | {…}
xs | '0.75rem' | {…}
```

My package.json

  ```
"dependencies": {
    "@expo/webpack-config": "^0.17.2",
    "@react-navigation/native": "^6.1.1",
    "@react-navigation/native-stack": "^6.9.7",
    "expo": "~47.0.9",
    "expo-status-bar": "~1.4.2",
    "react": "18.1.0",
    "react-dom": "18.1.0",
    "react-hook-form": "^7.41.5",
    "react-native": "0.70.5",
    "react-native-safe-area-context": "4.4.1",
    "react-native-screens": "~3.18.0",
    "react-native-web": "~0.18.9",
    "tailwind-react-native-classnames": "^1.5.1"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "tailwindcss": "^3.2.4"
  },
```

Did you spot anything from my code?  or any other thing I should look at?

**Comment by jaredh159** [comment]
ah, you've got the old name/version of the library installed, the package name is `twrnc` _not_ `tailwind-react-native-classnames`, run this:

```
npm uninstall tailwind-react-native-classnames
npm install twrnc
```

**Comment by nassmim** [comment]
@jaredh159 here we go! Thanks very much it works now! 🤩
